var eRenderContextMethod =
{
	Unknown									: 0,
	
	SetGlobalState							: 1,
    EnableRenderMode						: 2,
    IsRenderModeEnabled						: 3,
    SetViewport								: 4,
    //GetViewport							: 5,
    Clear									: 6,
    SetMatrixMode							: 7,
    PushMatrix								: 8,
    PopMatrix								: 9,
    LoadMatrix								: 10,
    MultMatrix								: 11,
    //GetMatrix								: 12,
    PerspectiveMatrixLH						: 13,
    PerspectiveMatrixRH						: 14,
    OrthographicMatrixLH					: 15,
    OrthographicMatrixRH					: 16,
    //GetMaxLightCount						: 17,
    SetLight								: 18,
    //GetLight								: 19,
    EnableLight								: 20,
    IsLightEnabled							: 21,
    SetEnabledLights						: 22,
    //GetEnabledLights						: 23,
    //GetMaxClipPlaneCount					: 24,
    //SetClipPlane							: 25,
    //GetClipPlane							: 26,
    //EnableClipPlane						: 27,
    //IsClipPlaneEnabled					: 28,
    //SetEnabledClipPlanes					: 29,
    //GetEnabledClipPlanes					: 30,
    SetGlobalIllumination					: 31,
    //GetGlobalIllumination					: 32,
    SetShadeModel							: 33,
    //GetShadeModel							: 34,
    SetColor								: 35,
    //GetColor								: 36,
    SetMaterial								: 37,
    //GetMaterial							: 38,
    SetBlendFactor							: 39,
    //GetMaxPrimitiveCount					: 40,
    //GetMaxVertexIndex						: 41,
    DrawPrimitives							: 42,
    CreateVertexBuffer						: 43,
    DeleteVertexBuffer						: 44,
    CreateIndexBuffer						: 45,
    DeleteIndexBuffer						: 46,
    CreateTexture							: 47,
    DeleteTexture							: 48,
    //GetMaxTextureStages					: 49,
    EnableTextureStage						: 50,
    SetTextureBlendOp						: 51,
    SetTextureBlendFactor					: 52,
    SetTextureWrap							: 53,
    SetTextureBorderColor					: 54,
    DrawSphere								: 55,
    DrawBox									: 56,
    //GetFrameBufferOrigin					: 57,
    ReadFrameBuffer							: 58,
    ReadAuxBuffer							: 59,
    WriteFrameBuffer						: 60,
    WriteAuxBuffer							: 61,
    SetPointSize							: 62,
    SetLineWidth							: 63,
    SupportsPixelFormat						: 64,
    SupportsAntialiasing					: 65,
    SetUserMaxTextureSize					: 66,
    //GetUserMaxTextureSize					: 67,
    SetFogParameters						: 68,
    //GetFogParameters						: 69,
    SetPolygonWindingOrder					: 70,
    //GetPolygonWindingOrder				: 71,
    ReversePolygonWindingOrder				: 72,
    SetDepthFunc							: 73,
    SetStencilFunc							: 74,
    SetStencilWriteMask						: 75,
    SetStencilOp							: 76,
    SetPolygonOffset						: 77,
    //GetPolygonOffset						: 78,
    //GetTransparentAlphaValue				: 79,
    CreateDisplayList						: 80,
    DeleteDisplayList						: 81,
    SetRenderTarget							: 82,

    /// VertexBufferObj
    VertexBufferObj_SetLength				: 83,
    VertexBufferObj_SetVertices				: 84,
    VertexBufferObj_SetVerticesVolatile		: 85,
    VertexBufferObj_SetColors				: 86,
    VertexBufferObj_SetColorsVolatile		: 87,
    VertexBufferObj_SetNormals				: 88,
    VertexBufferObj_SetNormalsVolatile		: 89,
    VertexBufferObj_SetUVCoords				: 90,
    VertexBufferObj_SetUVCoordsVolatile		: 91,
    VertexBufferObj_SetTextureStage			: 92,
    VertexBufferObj_Draw					: 93,
    VertexBufferObj_DrawIndexed				: 94,

    /// IndexBufferObj
    IndexBufferObj_SetLength				: 95,
    //IndexBufferObj_GetLength				: 96,
    IndexBufferObj_SetIndices				: 97,
    IndexBufferObj_SetIndicesVolatile		: 98,

    /// TextureObj
    //TextureObj_SetImage					: 99,
    //TextureObj_SetSubImage				: 100
}

function RenderContextMethodDesc()
{
	
}
